name: build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: >
          sudo apt-get -y install g++ pkg-config scons ragel gengetopt \
            libuv1-dev libunwind-dev libpulse-dev libsox-dev libcpputest-dev libtool \
            intltool autoconf automake make cmake

      - name: Build Roc
        run: |
          git clone --single-branch --branch ${GITHUB_REF##*/} \
              https://github.com/roc-streaming/roc-toolkit.git /tmp/roc
          scons -C /tmp/roc -Q --build-3rdparty=openfec
          sudo scons -C /tmp/roc -Q --build-3rdparty=openfec install

      - name: Build tests
        run: |
          mkdir build
          cd build
          cmake ..
          make -j$(nproc --all)
          test -e ../bin/rt-tests
